### ISSUE TITLE
How to create remote themes?

### ISSUE THREAD

**Issue by cakriwut** [nonblocking/mashroom#101]
Hi team,

I am curious if it is possible to create remote themes. If yes, is there any guide / sample?

Thanks in advance.

**Comment by nonblocking** [comment]
Hi,

No, it's not possible and I'm not sure if it would make sense from a performance and reliability perspective. Because with a remote theme the initial page rendering would rely on an external site. 

But you could of course periodically copy the theme from a remote server, Mashroom will pick up the changes if you set the "watch" property on true for the pluginPackageFolder where the theme resides. 

Regards

**Comment by cakriwut** [comment]
Thanks .
