### ISSUE TITLE
Question - React Remote App Client Side Rendering Router

### ISSUE THREAD

**Issue by cakriwut** [nonblocking/mashroom#103]
Does mashroom support react remote app that implement react-router (https://reactrouter.com/en/main/router-components/router)?

Is there any sample that I can follow?

Thanks,

Riwut

**Comment by nonblocking** [comment]
In general there are no restrictions what libraries you can use in a App that shall be integrated in Mashroom. So, of course you can use react-router.

That said, it might be a bit dangerous to allow Microfrontends to "take over" the address bar in the browser, because like this they could interfere with each other. At least you have to make sure only one Microfrontend on a page uses routing, which could reduce the possibilities of re-use. But you can use the MemoryRouter to circumvent this problem.

If you really want to use the BrowserRouter you have to activate "Allow client-side routing" in the page configuration:
<img width="499" alt="Screenshot 2022-11-22 at 11 48 17" src="https://user-images.githubusercontent.com/3135918/203295240-fbfb8fea-c53e-4433-87d3-e0319a1695e4.png">

**Comment by cakriwut** [comment]
Thanks for the explanation.

Thinking aloud, would it be possible to have route path defined in the RemoteApp's mashroom.json , that will be translated by the portal into sub-route.

Example:  A remote app is having / and /settings , will define mashroom.json like

```json
{
   ...
   "routes" : [ "/", "/settings" ]
}
```

Then, when the app is added to Mashroom Portal in /test1 , it will automatically recognize  /test1/AppID/ and /test1/AppID/settings to be forwarded to the RemoteApp.

**Comment by cakriwut** [comment]
Thanks for the explaination.
I can see the sandbox app is using stateservice.
