### ISSUE TITLE
Best practices for state management and routing

### ISSUE THREAD

**Issue by enclar** [nonblocking/mashroom#117]
Hi, I had some queries regarding best practices for state management and routing.

**Use Case 1**
I'm using **messageBus** to pass state information between multiple applications, but the state management is getting quite complex.
Is there a better way to handle transfer and sharing of data between many apps (eg. global mashroom state or something similar)?

**Use Case 2**
I am displaying data cards in an infinite scroll and can also set filters to this set of data cards. In a non-mashroom application, if I were to navigate away and back from this page (via the browser routing), my position in the infinite scroll and filters would be preserved. However, due to the application reloading in mashroom, I'm not able to retain the filter settings and infinite scroll positions. 
Is there a way to preserve the infinite scroll and filter state without passing the info from app1 to app2 and back to app1 again?

Thank you for your advice!

**Comment by nonblocking** [comment]
Well, actually it is a good thing to have no "shared state" between Microfrontends, because it increases the coupling and typically also limits the re-use.

That said, I see two options here:

- Encode your shared state in the URL using _portalClientServices.stateService.setUrlStateProperty()_. So, the idea would be to encode any state change in the URL and the other apps either listen to URL changes or get notified via _messageBus_ about the change. If the user now hits F5 or navigates back and forth that state persists.
- Encode your shared state in the browser's session storage. All your apps could just listen to changes there and load it at startup. You could again use the _stateService_ or just directly _global.sessionStorage_

Both approaches should cover both of your cases.

**Comment by enclar** [comment]
Thank you for your response!
