### ISSUE TITLE
vhost path mapping plugin

### ISSUE THREAD

**Issue by Enrice** [nonblocking/mashroom#121]
could (or should) consider not only host (and port, if given) from several standard or nonstandard host headers, but also the protocol which usually comes from the de-facto standard 'X-Forwarded-Proto' header.
Furthermore, it could also take the RFC standardized 'Forwarded' header into consideration.

**Comment by nonblocking** [comment]
Just talked with @Enrice to understand the problem with the protocol: It concerns only the reverse mapping of the *location* header. Backends cannot know the actual frontend protocol and might just send an http:// URL, in that case the vhost plugin could "fix" the protocol to avoid an extract roundtrip when the reverse proxy has to redirect to https again

**Comment by nonblocking** [comment]
The problem with the wrong protocol in the *location* header should be fixed with commit 883db14, which basically replaces such location URLs by the relative path. 

We won't support the RFC 7239 *Forwarded* header because it is very difficult to parse properly (and easy to sabotage) and therefor not supported by most reverse proxies. See [ngnix](https://forum.nginx.org/read.php?29,275880,275880#msg-275880) and this [post](https://adam-p.ca/blog/2022/03/forwarded-header-sabotage/)
